apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: civo.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: clusters.kubernetes.civo.kubeform.com
spec:
  group: kubernetes.civo.kubeform.com
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  apiEndpoint:
                    type: string
                  applications:
                    description: a comma separated list of applications to install.Spaces
                      within application names are fine, but shouldn't be either side
                      of the comma.Application names are case-sensitive; the available
                      applications can be listed with the civo CLI:'civo kubernetes
                      applications ls'.If you want to remove a default installed application,
                      prefix it with a '-', e.g. -Traefik.
                    type: string
                  createdAt:
                    type: string
                  dnsEntry:
                    type: string
                  id:
                    type: string
                  installedApplications:
                    items:
                      properties:
                        application:
                          type: string
                        category:
                          type: string
                        installed:
                          type: boolean
                        version:
                          type: string
                      type: object
                    type: array
                  instances:
                    items:
                      properties:
                        cpuCores:
                          format: int64
                          type: integer
                        diskGb:
                          format: int64
                          type: integer
                        hostname:
                          type: string
                        ramMb:
                          format: int64
                          type: integer
                        size:
                          type: string
                        status:
                          type: string
                        tags:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                  kubeconfig:
                    type: string
                  kubernetesVersion:
                    description: the version of k3s to install (optional, the default
                      is currently the latest available)
                    type: string
                  masterIP:
                    type: string
                  name:
                    description: a name for your cluster, must be unique within your
                      account (required)
                    type: string
                  networkID:
                    description: The network for the cluster, if not declare we use
                      the default one
                    type: string
                  numTargetNodes:
                    description: the number of instances to create (optional, the
                      default at the time of writing is 3)
                    format: int64
                    type: integer
                  pools:
                    items:
                      properties:
                        ID:
                          type: string
                        count:
                          format: int64
                          type: integer
                        instanceNames:
                          items:
                            type: string
                          type: array
                        instances:
                          items:
                            properties:
                              cpuCores:
                                format: int64
                                type: integer
                              diskGb:
                                format: int64
                                type: integer
                              hostname:
                                type: string
                              ramMb:
                                format: int64
                                type: integer
                              size:
                                type: string
                              status:
                                type: string
                              tags:
                                items:
                                  type: string
                                type: array
                            type: object
                          type: array
                        size:
                          type: string
                      type: object
                    type: array
                  ready:
                    type: boolean
                  region:
                    description: The region for the cluster, if not declare we use
                      the region in declared in the provider
                    type: string
                  status:
                    type: string
                  tags:
                    description: a space separated list of tags, to be used freely
                      as required (optional)
                    type: string
                  targetNodesSize:
                    description: the size of each node (optional, the default is currently
                      g2.k3s.medium)
                    type: string
                type: object
              state:
                properties:
                  apiEndpoint:
                    type: string
                  applications:
                    description: a comma separated list of applications to install.Spaces
                      within application names are fine, but shouldn't be either side
                      of the comma.Application names are case-sensitive; the available
                      applications can be listed with the civo CLI:'civo kubernetes
                      applications ls'.If you want to remove a default installed application,
                      prefix it with a '-', e.g. -Traefik.
                    type: string
                  createdAt:
                    type: string
                  dnsEntry:
                    type: string
                  id:
                    type: string
                  installedApplications:
                    items:
                      properties:
                        application:
                          type: string
                        category:
                          type: string
                        installed:
                          type: boolean
                        version:
                          type: string
                      type: object
                    type: array
                  instances:
                    items:
                      properties:
                        cpuCores:
                          format: int64
                          type: integer
                        diskGb:
                          format: int64
                          type: integer
                        hostname:
                          type: string
                        ramMb:
                          format: int64
                          type: integer
                        size:
                          type: string
                        status:
                          type: string
                        tags:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                  kubeconfig:
                    type: string
                  kubernetesVersion:
                    description: the version of k3s to install (optional, the default
                      is currently the latest available)
                    type: string
                  masterIP:
                    type: string
                  name:
                    description: a name for your cluster, must be unique within your
                      account (required)
                    type: string
                  networkID:
                    description: The network for the cluster, if not declare we use
                      the default one
                    type: string
                  numTargetNodes:
                    description: the number of instances to create (optional, the
                      default at the time of writing is 3)
                    format: int64
                    type: integer
                  pools:
                    items:
                      properties:
                        ID:
                          type: string
                        count:
                          format: int64
                          type: integer
                        instanceNames:
                          items:
                            type: string
                          type: array
                        instances:
                          items:
                            properties:
                              cpuCores:
                                format: int64
                                type: integer
                              diskGb:
                                format: int64
                                type: integer
                              hostname:
                                type: string
                              ramMb:
                                format: int64
                                type: integer
                              size:
                                type: string
                              status:
                                type: string
                              tags:
                                items:
                                  type: string
                                type: array
                            type: object
                          type: array
                        size:
                          type: string
                      type: object
                    type: array
                  ready:
                    type: boolean
                  region:
                    description: The region for the cluster, if not declare we use
                      the region in declared in the provider
                    type: string
                  status:
                    type: string
                  tags:
                    description: a space separated list of tags, to be used freely
                      as required (optional)
                    type: string
                  targetNodesSize:
                    description: the size of each node (optional, the default is currently
                      g2.k3s.medium)
                    type: string
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
