apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: civo.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: instances.instance.civo.kubeform.com
spec:
  group: instance.civo.kubeform.com
  names:
    kind: Instance
    listKind: InstanceList
    plural: instances
    singular: instance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  cpuCores:
                    format: int64
                    type: integer
                  createdAt:
                    type: string
                  diskGb:
                    format: int64
                    type: integer
                  firewallID:
                    description: The ID of the firewall to use, from the current list.
                      If left blank or not sent, the default firewall will be used
                      (open to all)
                    type: string
                  hostname:
                    description: A fully qualified domain name that should be set
                      as the instance's hostname (required)
                    type: string
                  id:
                    type: string
                  initialPassword:
                    type: string
                  initialUser:
                    description: The name of the initial user created on the server
                      (optional; this will default to the template's default_username
                      and fallback to civo)
                    type: string
                  networkID:
                    description: This must be the ID of the network from the network
                      listing (optional; default network used when not specified)
                    type: string
                  notes:
                    description: Add some notes to the instance
                    type: string
                  privateIP:
                    type: string
                  pseudoIP:
                    type: string
                  publicIP:
                    type: string
                  publicIPRequired:
                    description: This should be either none, create or `move_ip_from:intances_id`
                      by default is create
                    type: string
                  ramMb:
                    format: int64
                    type: integer
                  region:
                    description: The region for the instance, if not declare we use
                      the region in declared in the provider
                    type: string
                  reverseDNS:
                    description: A fully qualified domain name that should be used
                      as the instance's IP's reverse DNS (optional, uses the hostname
                      if unspecified)
                    type: string
                  script:
                    description: the contents of a script that will be uploaded to
                      /usr/local/bin/civo-user-init-script on your instance, read/write/executable
                      only by root and then will be executed at the end of the cloud
                      initialization
                    type: string
                  size:
                    description: The name of the size, from the current list, e.g.
                      g2.small (required)
                    type: string
                  sourceID:
                    type: string
                  sourceType:
                    type: string
                  sshkeyID:
                    description: The ID of an already uploaded SSH public key to use
                      for login to the default user (optional; if one isn't provided
                      a random password will be set and returned in the initial_password
                      field)
                    type: string
                  status:
                    type: string
                  tags:
                    description: An optional list of tags, represented as a key, value
                      pair
                    items:
                      type: string
                    type: array
                  template:
                    description: The ID for the template to use to build the instance
                    type: string
                type: object
              state:
                properties:
                  cpuCores:
                    format: int64
                    type: integer
                  createdAt:
                    type: string
                  diskGb:
                    format: int64
                    type: integer
                  firewallID:
                    description: The ID of the firewall to use, from the current list.
                      If left blank or not sent, the default firewall will be used
                      (open to all)
                    type: string
                  hostname:
                    description: A fully qualified domain name that should be set
                      as the instance's hostname (required)
                    type: string
                  id:
                    type: string
                  initialPassword:
                    type: string
                  initialUser:
                    description: The name of the initial user created on the server
                      (optional; this will default to the template's default_username
                      and fallback to civo)
                    type: string
                  networkID:
                    description: This must be the ID of the network from the network
                      listing (optional; default network used when not specified)
                    type: string
                  notes:
                    description: Add some notes to the instance
                    type: string
                  privateIP:
                    type: string
                  pseudoIP:
                    type: string
                  publicIP:
                    type: string
                  publicIPRequired:
                    description: This should be either none, create or `move_ip_from:intances_id`
                      by default is create
                    type: string
                  ramMb:
                    format: int64
                    type: integer
                  region:
                    description: The region for the instance, if not declare we use
                      the region in declared in the provider
                    type: string
                  reverseDNS:
                    description: A fully qualified domain name that should be used
                      as the instance's IP's reverse DNS (optional, uses the hostname
                      if unspecified)
                    type: string
                  script:
                    description: the contents of a script that will be uploaded to
                      /usr/local/bin/civo-user-init-script on your instance, read/write/executable
                      only by root and then will be executed at the end of the cloud
                      initialization
                    type: string
                  size:
                    description: The name of the size, from the current list, e.g.
                      g2.small (required)
                    type: string
                  sourceID:
                    type: string
                  sourceType:
                    type: string
                  sshkeyID:
                    description: The ID of an already uploaded SSH public key to use
                      for login to the default user (optional; if one isn't provided
                      a random password will be set and returned in the initial_password
                      field)
                    type: string
                  status:
                    type: string
                  tags:
                    description: An optional list of tags, represented as a key, value
                      pair
                    items:
                      type: string
                    type: array
                  template:
                    description: The ID for the template to use to build the instance
                    type: string
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
